import org.apache.hadoop.ipc.protocolPB.RefreshCallQueueProtocolClientSideTranslatorPB;
public class FunctionUse10167 {
public void funcUse() {
RefreshCallQueueProtocolClientSideTranslatorPB refreshcallqueueprotocolclientsidetranslatorpb = new RefreshCallQueueProtocolClientSideTranslatorPB();
refreshcallqueueprotocolclientsidetranslatorpb.isMethodSupported(null);
}
}