import org.apache.hadoop.security.protocolPB.RefreshAuthorizationPolicyProtocolClientSideTranslatorPB;
public class FunctionUse14230 {
public void funcUse() {
RefreshAuthorizationPolicyProtocolClientSideTranslatorPB refreshauthorizationpolicyprotocolclientsidetranslatorpb = new RefreshAuthorizationPolicyProtocolClientSideTranslatorPB();
refreshauthorizationpolicyprotocolclientsidetranslatorpb.isMethodSupported(null);
}
}